Corrected IsWorking NullReferenceException
rosenbjerg/FFMpegCore pull request #15
Opened 2019-06-14 14:44 UTC by Duke02

Also added test to ensure that it works.

2019-06-14 14:45 UTC, Duke02 commented
I should add that this attempts to fix #14

2019-06-18 10:31 UTC, vladjerca approved these changes

2019-06-18 10:33 UTC, vladjerca requested changes
@Duke02 Seems that the tests are failing? Seems to be related to the imported namespaces.

They fail on both `Linux` and `OSX`, same error.

More details here: https://travis-ci.org/vladjerca/FFMpegCore/builds/545786272?utm_source=github_status&utm_medium=notification

LE:

After cloning your `fork`, I found what's missing, just add the following imports to the `test file`. (strange that you didn't get a build error locally 😕)

```csharp
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
```

Also, after importing the required namespaces, I noticed all of the other tests fail due to the modified code.

2019-06-18 16:22 UTC, vladjerca requested changes

2019-06-18 16:22 UTC, vladjerca commented on FFMpegCore/FFMPEG/FFBase.cs
> +                return true;
This should implicitly return `false`. This is why all of the tests currently fail 😬

2019-07-17 19:50 UTC, vladjerca commented
@Duke02 Are you still working on this issue?

2019-07-18 14:46 UTC, Duke02 commented
No I am not. Sorry.

2019-09-29 21:07 UTC, closed without merging