Using correct map_metadata dynamically
rosenbjerg/FFMpegCore pull request #292
Opened 2022-01-11 21:44 UTC by JKamsker

Found out, that it matters which number comes after the map_metadata. 
Had to change quite a bit in order to put in the correct number

2022-01-11 23:32 UTC, JKamsker commented
A unit test just saved my ass lol

2022-01-20 21:36 UTC, rosenbjerg commented on FFMpegCore/Extend/StringExtensions.cs
> +            if (substring.Length > s.Length)
Move `substring.Length > s.Length` into the first if for brevity and remove comments (documentation comment is okay)

2022-01-20 21:38 UTC, rosenbjerg commented on FFMpegCore/FFMpeg/Arguments/MetaDataArgument.cs
> +        public string GetText(StringBuilder context)
Just use `string` instead of `StringBuilder` here. Fits together with my comment below

2022-01-20 21:43 UTC, rosenbjerg commented on FFMpegCore/FFMpeg/FFMpegArguments.cs
> +            var sb = new StringBuilder();
Maybe change impl to 

```csharp
var allArguments = _globalArguments.Arguments.Concat(Arguments).ToArray();
return string.Join(" ", allArguments.Select(arg => arg is IDynamicArgument dynArg ? dynArg.GetText(allArguments) : arg.Text));
```

2022-01-20 21:46 UTC, rosenbjerg commented on FFMpegCore/FFMpeg/Arguments/IDynamicArgument.cs
> +        public string GetText(StringBuilder context);
Change to take IArgument[] as input instead. That should also allow much more concise check ie. using .OfType<IInputArgument>().Any() or similar. Fits together with me comment below

2022-01-20 21:46 UTC, rosenbjerg requested changes
I have put some comments :)

2022-01-20 21:48 UTC, rosenbjerg commented
> A unit test just saved my ass lol

That's why we love 'em

2022-01-20 21:56 UTC, rosenbjerg commented on FFMpegCore/Extend/StringExtensions.cs
> +        public static int CountOccurrences(this string s, string substring,
Should not be needed

2022-01-20 21:57 UTC, rosenbjerg commented on FFMpegCore/Extend/StringExtensions.cs
> +        public static int CountOccurrences(this string s, string substring,
I mean the entire function should not be needed when passing IArgument[] since that allows for much better checking

2022-03-01 23:19 UTC, rosenbjerg commented
@JKamsker

2022-03-10 01:01 UTC, JKamsker commented
Eh yes yes yes i didnt forget about it, i just didn't have time for it yet, im sorry 😅

2022-03-20 18:32 UTC, JKamsker commented
Updated, tests ran through.

Thanks for your suggestion to use IInputArgument instead of string counting^^

2022-03-24 20:04 UTC, merged

2022-03-24 20:12 UTC, rosenbjerg commented
Merged! Thanks for the contribution!